language: python
python:
  - 2.7
  - 3.4
  - 3.5
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e ".[testing]"
  - pip install -e .
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=eitbapi setup.py test
after_success:
  - coveralls
