language: python
python:
  - 2.7
  - 3.5
  - 3.6
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e ".[testing]"
  - pip install -e .
# command to run tests
script:
  coverage run --source=eitbapi setup.py test
after_success:
  - pip install coveralls
  - coveralls
